### ISSUE TITLE
Feature Request: Support Drupal multisite w/ drush --uri option

### ISSUE THREAD

**Issue by pianomansam** [cytopia/check_drupal#1]
Would it be possible to pass in an --uri option to drush so this could support drupal multisite?

**Comment by cytopia** [comment]
Can u checkout branch `feature/multisite` and see if it is working as expected?
I do not have any multisite setup around to test.

**Comment by pianomansam** [comment]
Yes, it seems to be working.

**Comment by cytopia** [comment]
OK, I will merge it into master then. Thanks for the info
