### ISSUE TITLE
Feature Request: Support NRPE output

### ISSUE THREAD

**Issue by pianomansam** [cytopia/check_drupal#2]
Using the check_by_ssh Nagios plugin is nice because you don't have to setup anything on the client server except drush and ssh. However, you need to make sure the Nagios can ssh into the client server. Having NRPE output support would eliminate the requirement for check_by_ssh and eliminate setting up ssh access on every client sever.

**Comment by cytopia** [comment]
could you reference some docs regarding nrpe please

**Comment by pianomansam** [comment]
@cytopia, thanks for the quick response! Actually, it looks like Nagios is very flexible with its output, and your script is doing a great job encoding the data. Much better than the [Nagios](https://www.drupal.org/project/nagios) and [Monitoring](https://www.drupal.org/project/monitoring) Drupal modules. So I'm going to go ahead and close this issue.

**Comment by pianomansam** [comment]
Just as a quick FYI, it looks like all Nagios plugins (including NRPE) should follow these output guidelines: https://nagios-plugins.org/doc/guidelines.html#PLUGOUTPUT
