### ISSUE TITLE
Option to pass a config file to drush

### ISSUE THREAD

**Issue by daften** [cytopia/check_drupal#7]
It would be handy (in our case) to have a --config (-c) option to pass a drushrc.php file to guide the drush commands. In our case, this is to make sure the language is dutch. This could provide an option to make sure the problem at https://github.com/cytopia/check_drupal/blob/master/bin/check_drupal#L366 can be circumvented.

I will create a PR for this later, unless I get a definitive no :)

**Comment by daften** [comment]
Opened: #8

**Comment by cytopia** [comment]
Yes this line was a problem. However, when you are able to pass a custom config, wouldn't it be worse? The user could accidentally choose a language that is not covered in that line.

Maybe I am getting this wrong...?
What about creating a temporary config, which sets the project to plain English.
This would also remove the need of checking against multiple languages in line 366.

**Comment by daften** [comment]
Well, it is documented that the config file can be used, if the documentation specifies that the language should be english (which IMO it should be server wide normally), it is up to the user to make sure this is allright.
Setting a temporary config file is an option as well, we do this during our deployment (atm, will probably change), but it feels a bit hacky as well. Would we write the drushrc file in the ~/.drush folder or the sites/<default or uri> folder? The latter could have problems if the uri's are matched in a sites.php file, so we wouldn't detect which actual folder is used (I think)

And thanks taking this into consideration ;)

**Comment by cytopia** [comment]
As I haven't used any config files yet, could you paste a very basic one here please which only adjusts the language.

**Comment by daften** [comment]
This one is extensive, but will work in every case:

```
<?php
// Drush commands should always be run in en.
$options['variables']['language_default'] = (object) array(
  'language' => 'en',
  'name' => 'English',
  'native' => 'English',
  'direction' => '0',
  'enabled' => 1,
  'plurals' => '0',
  'formula' => '',
  'domain' => '',
  'prefix' => 'en',
  'weight' => '0',
  'javascript' => '',
);
```

A simplified that might give issues:

```
<?php 
$options['variables']['language_default']->language = 'en'; 
```

**Comment by cytopia** [comment]
I just tried this for a few drupal (D7) projects (which default to German). Works like a charm with a forced configuration.

I guess (depending on whether it will work for D6, D7 and D8) it will be the best case to create a radnomly-named configuration on the fly in /tmp (only with the above language specifications). At the end of the program, it must be deleted as well. This way all language specific `greps` can be removed from the source code.

**Comment by daften** [comment]
Ok, let me try to cook something up. :)

**Comment by daften** [comment]
BTW: this wil mean the end user will have no option in the language for the output if we force this. So if somebody would want german, dutch, ... as the output language for warnings, it's not possible.

**Comment by cytopia** [comment]
The `check_drupal` needs to be able to interpret the output language of drush.
You would need to implement all languages in `grep` for example to look for either "Warning" or "Warnung" or whatever it is in the other languages.

Best is to use drupals english default to be able to know exactly what is going on. The output of `check_drupal` is anyway just machine-readable code for nagios/icinga. But if you want to change the leading "ERROR, WARNING, UNKNOWN, OK" thats a different thing.

**Comment by cytopia** [comment]
> So if somebody would want german, dutch, ... as the output language for warnings, it's not possible.

Could be, but way more difficult.
I guess we are talking about two different things.
1. I wanted to make sure that drush always reports back in english, so I can pass the output with `grep` and similar tools and assign variables accordingly inside the code.
2. You wanted to have the actual output in Dutch for the nagios display (by letting drush report back in Dutch).

So the first one is a must-have and fixes the current code. The second one could be implemented additionally somehow.

**Comment by daften** [comment]
No, I don't want the output in dutch, but some people could want the output in their native language I think :)
The second one could be implemented otherwise, but I guess if people need it, they will ask for it and hopefully create a PR.

I'm working on the first option right now, almost done ;)

**Comment by daften** [comment]
And #9 is made ;)
I'm not great at bash scripting, so feel free to give harsh feedback :p

**Comment by cytopia** [comment]
Thanks a lot. I am going to merge that later. 👍

**Comment by daften** [comment]
Excellent, thanks for that (and the quick follow-up) ;)

**Comment by cytopia** [comment]
Thanks for the work. #9 is merged.
